route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: <Email-Addr-Of-Receivers>
    from: <Email-Addr-Of-Sender>
    smarthost: smtp.gmail.com:587
    auth_username: "<Email-Addr-Of-Sender>"
    auth_identity: "<Email-Addr-Of-Sender>"
    auth_password: "<Email-Addr-Password-Of-Sender>"
