route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: farshidzamanirad@gmail.com
    from: farshidz1100@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "farshidz1100@gmail.com"
    auth_identity: "farshidz1100@gmail.com"
    auth_password: "Fzr72367407@#"